steps:
  - name: Update Composer
    command: '/usr/local/bin/composer self-update'
  - name: Require drush 8.1.15.
    command: 'cd /src/docroot && composer global require drush/drush:8.1.15'
  - name: Run the profile script
    command: './$SRC_DIR/.probo-profile-build.sh'
  - name: Run install
    command: "drush site-install --root=/var/www/html bear --db-url='mysqli://root:strongpassword@localhost/bear'"
  - name: Set file directory permissions
    command: 'chown -R www-data:www-data /var/www/html/sites/default/files'
  - name: Rebuild caches
    command: 'drush cr'
  - name: Run behat tests
    command: 'cd /var/www/html/profiles/bear/tests ; composer install ; ./bin/behat --profile probo'
