image: proboci/ubuntu-16.04-lamp:php7.1-nightly
steps:
  - name: Update Composer
    command: '/usr/local/bin/composer self-update'
  - name: Require drush 8.1.15.
    command: 'composer global require drush/drush:8.1.15'
  - name: Install composer packages with dependencies.
    command: 'composer install -d /var/www/html'
 - name: Probo site setup
    plugin: Drupal
    configSyncDirectory: config/sync
    drupalVersion: 8
    runInstall: bear
  - name: Set file directory permissions
    command: 'chown -R www-data:www-data /var/www/html/sites/default/files'
  - name: Rebuild caches
    command: 'drush cr'
  - name: Run behat tests
    command: 'cd /var/www/html/profiles/bear/tests ; composer install ; ./bin/behat --profile probo'
