; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Profiles
projects[bear][type] = "profile"
projects[bear][download][type] = "get"
projects[bear][download][url] = "file:///var/www/drupal_site/code/bear"