; This file was auto-generated by drush make
core = 7.x

api = 2
; Modules
projects[ctools][version] = "1.2"

projects[diff][version] = "3.2"

projects[ds][version] = "2.0"

projects[entity][version] = "1.0-rc3"

projects[entityreference][version] = "1.0"

projects[field_group][version] = "1.1"

projects[file_entity][version] = "2.0-unstable7"

projects[media][version] = "1.2"

projects[menu_block][version] = "2.3"

projects[menu_position][version] = "1.1"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[strongarm][version] = "2.0"

projects[styleguide][version] = "1.0"

projects[token][version] = "1.4"

projects[wysiwyg][version] = "2.2"

; Themes
projects[survivalkit][version] = "1.x-dev"

; Libraries
libraries[tinymce][download][type] = "file"
libraries[tinymce][download][url] = "https://github.com/downloads/tinymce/tinymce/tinymce_3.5.8.zip"
libraries[tinymce][destination] = "libraries"

