<?php
/**
 * @file
 * Code for the Bear Necessities feature.
 */

include_once 'bear_necessities.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bear_necessities_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  if (array_key_exists('is_new', $form['#node_type'])) {
    // Set 'Preview before submitting' to disabled.
    $form['submission']['node_preview']['#default_value'] = DRUPAL_DISABLED;

    // Set publishing options.
    $form['workflow']['node_options']['#default_value'] = array('status', 'revision');

    // Unset display author information.
    $form['display']['node_submitted']['#default_value'] = FALSE;

    // Set comments to hidden.
    if (module_exists('comment')) {
      $form['comment']['comment']['#default_value'] = COMMENT_NODE_HIDDEN;
    }
  }
}

/*
 * Implements hook_form_alter().
 */
function bear_necessities_form_node_form_alter(&$form, &$form_state, $form_id) {
  // We want to hide revision information
  // from people that do not have right
  // to view Content Revision.
  if (!user_access('view revisions')) {
    if (isset($form['revision_information']['#access'])) {
      $form['revision_information']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bear_necessities_form_ckeditor_admin_profile_form_alter(&$form, &$form_state) {
  // By default turn off CKEditor's "Advanced Content Filter" which removes
  // html tags that do not have wysiwyg buttons enabled.
  if (empty($form['advanced']['js_conf']['#default_value'])) {
    $form['advanced']['js_conf']['#default_value'] = 'config.allowedContent = true;';
  }
}
