<?php
/**
 * @file
 * Code for the Bear Necessities feature.
 */

include_once 'bear_necessities.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bear_necessities_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  if (empty($form['#node_type']->type)) {
    // Set 'Preview before submitting' to disabled.
    $form['submission']['node_preview']['#default_value'] = DRUPAL_DISABLED;

    // Set publishing options.
    $form['workflow']['node_options']['#default_value'] = array('status', 'revision');

    // Unset display author information.
    $form['display']['node_submitted']['#default_value'] = FALSE;

    // Set comments to hidden.
    if (module_exists('comment')) {
      $form['comment']['comment']['#default_value'] = COMMENT_NODE_HIDDEN;
    }
  }
}

/*
 * Implements hook_node_form_alter().
 */
function bear_necessities_form_node_form_alter(&$form, &$form_state) {
  // We want to hide revision information from people that do not have permission
  // to view content revisions.
  if (module_exists('workbench_moderation') && isset($form['revision_information']['workbench_moderation_state_new'])) {
    return;
  }
  if (!user_access('view revisions')) {
    if (isset($form['revision_information']['#access'])) {
      $form['revision_information']['#access'] = FALSE;
    }
  }
  // Remove 'promote to frontpage' and 'make sticky' options.
  unset($form['options']['sticky']);
  unset($form['options']['promote']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bear_necessities_form_ckeditor_admin_profile_form_alter(&$form, &$form_state) {
  // By default turn off CKEditor's "Advanced Content Filter" which removes
  // html tags that do not have wysiwyg buttons enabled.
  if (empty($form['advanced']['js_conf']['#default_value'])) {
    $form['advanced']['js_conf']['#default_value'] = 'config.allowedContent = true;';
  }
}

/**
 * Implements hook_menu_block_blocks().
 */
function bear_necessities_menu_block_blocks() {
  return array(
    'bear_necessities-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => '',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}
